---
name: CI

on:
  push:
    branches:
      - main
      - *
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up tools
      run: sudo apt-get install -y make bats shfmt shellcheck

    - name: Format code
      run: make format

    - name: Lint code
      run: make lint

    - name: Run tests
      run: make test

